# Generated by Django 5.1.6 on 2025-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PassengerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Discount percentage"
                    ),
                ),
                (
                    "requires_document",
                    models.BooleanField(default=True, verbose_name="Requires document"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Display order"
                    ),
                ),
            ],
            options={
                "verbose_name": "Passenger Type",
                "verbose_name_plural": "Passenger Types",
                "ordering": ["order", "name"],
            },
        ),
    ]
