# Generated by Django 5.1.6 on 2025-03-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_passengertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="passenger_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tickets",
                to="booking.passengertype",
                verbose_name="Passenger type",
            ),
        ),
    ]
