# Generated by Django 5.1.6 on 2025-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of station"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
                "ordering": ["name"],
            },
        ),
    ]
