# Generated by Django 5.1.6 on 2025-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0002_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of train"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Train number"
                    ),
                ),
                (
                    "train_type",
                    models.CharField(
                        choices=[
                            ("passenger", "Passenger"),
                            ("express", "Express"),
                            ("suburban", "Suburban"),
                        ],
                        default="passenger",
                        max_length=20,
                        verbose_name="Train type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Train",
                "verbose_name_plural": "Trains",
            },
        ),
    ]
