# Generated by Django 5.1.6 on 2025-03-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_train"),
    ]

    operations = [
        migrations.CreateModel(
            name="WagonAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Amenity name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Wagon Amenity",
                "verbose_name_plural": "Wagon Amenities",
            },
        ),
        migrations.CreateModel(
            name="WagonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of wagon type"),
                ),
                (
                    "fare_multiplier",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="Fare multiplier"
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagon type",
                "verbose_name_plural": "Wagon types",
            },
        ),
        migrations.CreateModel(
            name="Wagon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(verbose_name="Wagon number"),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(verbose_name="Number of seats"),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wagons",
                        to="station.train",
                        verbose_name="Train",
                    ),
                ),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wagons",
                        to="station.wagonamenity",
                        verbose_name="Amenities",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wagons",
                        to="station.wagontype",
                        verbose_name="Wagon type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wagon",
                "verbose_name_plural": "Wagons",
                "unique_together": {("train", "number")},
            },
        ),
    ]
