# Generated by Django 5.1.6 on 2025-03-19 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_trip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wagon",
            old_name="type",
            new_name="wagon_type",
        ),
    ]
